### ISSUE TITLE
Short-term todo

### ISSUE THREAD

**Issue by magicant** [magicant/yash3#1]
### Using Result::Err for unrecoverable errors only

- [x] Consider not using ErrorCause::Unknown in favor of Option
  - [x] Parser::redirection should return Option
- [x] Parser::peek_token should return `Result<&Token>`

### Here-doc

- [x] Parse here-doc operator in lexer
  - [x] TokenId::Operator
  - [x] Operator parser (using trie)
- [x] Parse here-doc redirection (operator and delimiter)
  - [x] Add EndOfInput to TokenId
  - [x] Basic implementation of Parser::redirection
  - [x] Tests of Parser::redirection
- [x] Parse redirection in simple command
- [x] Parse NEWLINE token
- [x] Remember pending here-doc in Parser
- [x] Add delimiter decider parameter to Lexer::word
- [x] Read here-doc content
  - [x] Move `PartialHereDoc` to crate::parser::lex::heredoc
  - [x] Implement Lexer::here_doc_content
  - [x] Rename Parser::remember_unread_here_doc
  - [x] Parser::here_doc_contents
  - [x] Parser::take_read_here_docs
  - [x] Parser::newline_and_here_doc_contents
  - [x] Fill iterator item should be without Result
  - [x] Parser::command_line
  - [x] Enable remaining tests in Parser.rs
  - [x] Use Parser::command_line in bin_main
- [x] [Test](https://github.com/magicant/yash3/blob/b5d4f0c8e4cbbe076b95e0837112a0497d466e51/src/parser.rs#L109) rememberd here-docs

### Restructuring

- ~~Move the `lex` module out of the `parser` module~~
- ~~Add `Any` as a super-trait of `Input`, so that the caller can regain the input object in the original type.~~

### Alias substitution

- [x] Define alias dictionary data structure
- [x] Add a alias dictionary to Parser (or Lexer?)
  - Probably the dictionary should be in the Parser rather than the Lexer, so that the temporary Parser for command substitution can have an empty dictionary.
- [x] Add Source::Alias
- [x] Input::next_line does not need to return Rc. It can be introduced by the caller.
- ~~IntoIterator for Line~~
- ~~Consider removing Line::enumerate~~
- [x] Source::Alias should have location of substituted word
- [x] Implement source substitution function in Lexer
- [x] Word::to_string_if_literal
- [x] Define a function to perform alias substitution in Parser
- [x] Return Rec from every function in Parser
- [x] Use the token index in alias substitution
- [x] Prevent recursive (infinite) substitution

### Command substitution

- [x] Define WordUnit::CommandSubst
- [x] Define a function that parses an entire command list in Parser, which will be the entry point for recursive parsing
- [x] Add index (position of the first character of the word) to Token
- ~~Parser::unpeek_token~~
- [x] Lexer::inner_program
- [x] Parse the command substitution
